var svg = d3.select(".WEEK_title")
    .append("svg")
    .attr('width', 1200)
    .attr('height', 100)
    .attr('transform','translate(180,0)')

    svg.append('text')
    .attr('x', 270)
    .attr('y', 80)
    .text('[ Crime occurrence by day of the week ]')
    .style('font-size', '23px')
    .attr("font-family", "sans-serif")
    .attr("font-weight", "bolder")
    .attr("fill", "black")
